wandb_version: 1

activation:
  value: relu
batch_size:
  value: 64
hidden_size:
  value:
  - 128
  - 64
learning_rate:
  value: 0.01
num_layers:
  value: 3
optimizer:
  value: nag
weight_init:
  value: random
